### PR TITLE
Modernize the project and make the CI green again

### PR DESCRIPTION
**Pull request by jeremiedimino**
To fix the CI and get everything to build (the benchmark was broken).

### CODE REVIEW

**Comment by jeremiedimino** [comment]
CI's passing now. @aalekseyev do you want to have a quick look at the diff for `test/test.ml` and `src/spawn.mli`? I adjusted things to get the Windows CI to pass and remove the warnings about doc comments.

**Comment by aalekseyev** [comment]
Looks good to me. Might be worth adding a comment about why the "prog relative to cwd" test doesn't work on windows (I actually don't know why).

Also, I think testing the error messages is somewhat useful. Maybe it makes sense to do a similar trick on windows? (rewrite Unix_error on windows into the one we expect)

**Comment by jeremiedimino** [comment]
Yeah, I don't why either :/ I disabled it because I got fed up of developing through the CI... (@dra27 we need your Windows expertise!).

> Also, I think testing the error messages is somewhat useful. Maybe it makes sense to do a similar trick on windows? (rewrite Unix_error on windows into the one we expect)

That seems good. I'll have a look at doing this!

**Comment by jeremiedimino** [comment]
Alright, as discussed I'm keeping the `_` printing for now until we can use 4.11 in the Windows CI, since older versions of OCaml don't register the printer for unix errors on Windows.

**Pull request merged**
